### ISSUE TITLE
Please add @throws phpdoc comments to helper functions

### ISSUE THREAD

**Issue by arthurshafikov** [PostScripton/Money#149]
It's not always clear that a helper function can throw an exception, it has to have a phpdoc @throws comment. 
![image](https://github.com/PostScripton/laravel-money/assets/60509074/33dcb88c-5af1-4b4c-aa0c-339e487d0c2e)

For example `lessThan` function has an indicator that it throws an exception, I can see from that that I have to deal with this Exception by myself.
![image](https://github.com/PostScripton/laravel-money/assets/60509074/cfc1382d-f966-4c2f-8cbf-3adeb9005fb2)

Also maybe you would like to add `is_valid_money_string()` function-helper or `money_validate()` to validate the string before parsing? I want to have a way of avoiding try/catch structures.

**Comment by PostScripton** [comment]
Hi, @arthurshafikov! Thank you for your the first issue on this repo.

I'll definitely add those exceptions to PHPDocs. 
Thank you for reporting that 👍🏻

Speaking of additional helper method, I'll think of adding it, this seems useful 😉

**Comment by PostScripton** [comment]
@arthurshafikov, I've got updates on your issue.

That's been fixed here: https://github.com/PostScripton/laravel-money/pull/150
And released in this version: [v4.1.1](https://github.com/PostScripton/laravel-money/releases/tag/v4.1.1)

I'll open a new issue for the new helper method that you've mentioned
