### ISSUE TITLE
Brazilian Real symbol position

### ISSUE THREAD

**Issue by piikenoo** [PostScripton/Money#81]
Hi! The currency symbol position in Brazilian Real must be at the start. Example: R$ 12.345,67

**Comment by PostScripton** [comment]
Hi, @piikenoo!
Fixed here: https://github.com/PostScripton/laravel-money/pull/84

Try it out a new version [`3.2.2`](https://github.com/PostScripton/laravel-money/releases/tag/v3.2.2)! 😄

**Comment by piikenoo** [comment]
Thank you, @PostScripton! Now everything is working perfectly.  :brazil: :thumbsup:
