### ISSUE TITLE
Using currency_list setting as custom doesn't work

### ISSUE THREAD

**Issue by piikenoo** [PostScripton/Money#82]
### Description:
```
The config value "money.currency_list" must be "all", "popular", "custom" or an array of codes. The value "custom" was given.
```

### Additional Context:
I noticed that the `isIncorrectList` method of the `PostScripton\Money\Currency` class is missing the `LIST_CUSTOM` constant. Will it be something related to this?

### Versions:
Laravel Version: 8.x
Laravel Money Version: 3.2
PHP Version: 7.4.28

### Steps To Reproduce:
1. Change `currency_list` to `custom` in `config/money.php`

**Comment by PostScripton** [comment]
Hi, @piikenoo! Thank you so much for reporting this bug.
Fixed here: https://github.com/PostScripton/laravel-money/pull/83

Try it out a new version [`3.2.1`](https://github.com/PostScripton/laravel-money/releases/tag/v3.2.1)!
